format = """
$username\
$hostname\
:\
$directory\
$git_branch\
$git_status\
$character
"""

add_newline = true
command_timeout = 100

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = true
format = '@[$hostname](bold cyan)'
disabled = false

[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[character]
success_symbol = "[❯](bold white)" 
error_symbol = "[❯](bold red)"
