{ ... }: {
  flake.nixosModules.nixbookHardware = { config, lib, pkgs, modulesPath, ... }:
    {
      # Do not modify this file!  It was generated by ‘nixos-generate-config’
      # and may be overwritten by future invocations.  Please make changes
      # to /etc/nixos/configuration.nix instead.
      imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];
    
      boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];
    
      fileSystems."/" =
        { device = "/dev/disk/by-uuid/e6c7301f-b59a-4900-8da2-e3467929bea5";
          fsType = "btrfs";
          options = [ "subvol=@" "compress=zstd:6" ];
        };
    
      fileSystems."/home" =
        { device = "/dev/disk/by-uuid/e6c7301f-b59a-4900-8da2-e3467929bea5";
          fsType = "btrfs";
          options = [ "subvol=@home" "compress=zstd:6" ];
        };
    
      fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/21A0-D56C";
          fsType = "vfat";
          options = [ "fmask=0077" "dmask=0077" ];
        };
    
      swapDevices = [ ];
    
      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
