[window]
opacity = 0.8
blur = true

[cursor]
blink_interval = 700

[cursor.style]
shape = "Underline"
blinking = "On"

[font]
size = 12

[font.bold]
family = "CaskaydiaCove NFM"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove NFM"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NFM"
style = "Regular"

[terminal]
osc52 = "CopyPaste"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[colors.primary]
foreground = "#dbdbdb"
background = "#000000"

[colors.normal]
black = "#464646"
red = "#b85252"
green = "#9ac794"
yellow = "#d7b191"
blue = "#9ca8d0"
magenta = "#b799b9"
cyan = "#8bb0b8"

[colors.bright]
black = "#464646"
red = "#b85252"
green = "#9ac794"
yellow = "#d7b191"
blue = "#9ca8d0"
magenta = "#b799b9"
cyan = "#8bb0b8"
